// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	db "nabi-auth/db/gen/queries.go"
	reflect "reflect"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
	isgomock struct{}
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// CreateAuthMethod mocks base method.
func (m *MockIRepository) CreateAuthMethod(ctx context.Context, userID pgtype.UUID, methodType db.AuthMethodType, methodData any) (db.AuthMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuthMethod", ctx, userID, methodType, methodData)
	ret0, _ := ret[0].(db.AuthMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAuthMethod indicates an expected call of CreateAuthMethod.
func (mr *MockIRepositoryMockRecorder) CreateAuthMethod(ctx, userID, methodType, methodData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuthMethod", reflect.TypeOf((*MockIRepository)(nil).CreateAuthMethod), ctx, userID, methodType, methodData)
}

// CreateOTPCode mocks base method.
func (m *MockIRepository) CreateOTPCode(ctx context.Context, userID pgtype.UUID, identifier, codeHash string, expiresAt pgtype.Timestamp) (db.OtpCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOTPCode", ctx, userID, identifier, codeHash, expiresAt)
	ret0, _ := ret[0].(db.OtpCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOTPCode indicates an expected call of CreateOTPCode.
func (mr *MockIRepositoryMockRecorder) CreateOTPCode(ctx, userID, identifier, codeHash, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOTPCode", reflect.TypeOf((*MockIRepository)(nil).CreateOTPCode), ctx, userID, identifier, codeHash, expiresAt)
}

// CreateSession mocks base method.
func (m *MockIRepository) CreateSession(ctx context.Context, userID pgtype.UUID, token, refreshToken string, expiresAt pgtype.Timestamp) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, userID, token, refreshToken, expiresAt)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockIRepositoryMockRecorder) CreateSession(ctx, userID, token, refreshToken, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockIRepository)(nil).CreateSession), ctx, userID, token, refreshToken, expiresAt)
}

// CreateUser mocks base method.
func (m *MockIRepository) CreateUser(ctx context.Context, email, phoneNumber, telegramUsername pgtype.Text, telegramID pgtype.Int8) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, email, phoneNumber, telegramUsername, telegramID)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIRepositoryMockRecorder) CreateUser(ctx, email, phoneNumber, telegramUsername, telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIRepository)(nil).CreateUser), ctx, email, phoneNumber, telegramUsername, telegramID)
}

// DeleteSession mocks base method.
func (m *MockIRepository) DeleteSession(ctx context.Context, sessionID pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockIRepositoryMockRecorder) DeleteSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockIRepository)(nil).DeleteSession), ctx, sessionID)
}

// DeleteSessionByRefreshToken mocks base method.
func (m *MockIRepository) DeleteSessionByRefreshToken(ctx context.Context, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSessionByRefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSessionByRefreshToken indicates an expected call of DeleteSessionByRefreshToken.
func (mr *MockIRepositoryMockRecorder) DeleteSessionByRefreshToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSessionByRefreshToken", reflect.TypeOf((*MockIRepository)(nil).DeleteSessionByRefreshToken), ctx, refreshToken)
}

// DeleteSessionByToken mocks base method.
func (m *MockIRepository) DeleteSessionByToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSessionByToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSessionByToken indicates an expected call of DeleteSessionByToken.
func (mr *MockIRepositoryMockRecorder) DeleteSessionByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSessionByToken", reflect.TypeOf((*MockIRepository)(nil).DeleteSessionByToken), ctx, token)
}

// GetAuthMethodByUserIDAndType mocks base method.
func (m *MockIRepository) GetAuthMethodByUserIDAndType(ctx context.Context, userID pgtype.UUID, methodType db.AuthMethodType) (db.AuthMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthMethodByUserIDAndType", ctx, userID, methodType)
	ret0, _ := ret[0].(db.AuthMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthMethodByUserIDAndType indicates an expected call of GetAuthMethodByUserIDAndType.
func (mr *MockIRepositoryMockRecorder) GetAuthMethodByUserIDAndType(ctx, userID, methodType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthMethodByUserIDAndType", reflect.TypeOf((*MockIRepository)(nil).GetAuthMethodByUserIDAndType), ctx, userID, methodType)
}

// GetOTPCodeByIdentifier mocks base method.
func (m *MockIRepository) GetOTPCodeByIdentifier(ctx context.Context, identifier string) (db.OtpCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOTPCodeByIdentifier", ctx, identifier)
	ret0, _ := ret[0].(db.OtpCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOTPCodeByIdentifier indicates an expected call of GetOTPCodeByIdentifier.
func (mr *MockIRepositoryMockRecorder) GetOTPCodeByIdentifier(ctx, identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOTPCodeByIdentifier", reflect.TypeOf((*MockIRepository)(nil).GetOTPCodeByIdentifier), ctx, identifier)
}

// GetSessionByRefreshToken mocks base method.
func (m *MockIRepository) GetSessionByRefreshToken(ctx context.Context, refreshToken string) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByRefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByRefreshToken indicates an expected call of GetSessionByRefreshToken.
func (mr *MockIRepositoryMockRecorder) GetSessionByRefreshToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByRefreshToken", reflect.TypeOf((*MockIRepository)(nil).GetSessionByRefreshToken), ctx, refreshToken)
}

// GetSessionByToken mocks base method.
func (m *MockIRepository) GetSessionByToken(ctx context.Context, token string) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByToken", ctx, token)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByToken indicates an expected call of GetSessionByToken.
func (mr *MockIRepositoryMockRecorder) GetSessionByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByToken", reflect.TypeOf((*MockIRepository)(nil).GetSessionByToken), ctx, token)
}

// GetUserByEmail mocks base method.
func (m *MockIRepository) GetUserByEmail(ctx context.Context, email string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockIRepositoryMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockIRepository)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockIRepository) GetUserByID(ctx context.Context, userID pgtype.UUID) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockIRepositoryMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockIRepository)(nil).GetUserByID), ctx, userID)
}

// GetUserByPhone mocks base method.
func (m *MockIRepository) GetUserByPhone(ctx context.Context, phoneNumber string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByPhone", ctx, phoneNumber)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByPhone indicates an expected call of GetUserByPhone.
func (mr *MockIRepositoryMockRecorder) GetUserByPhone(ctx, phoneNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByPhone", reflect.TypeOf((*MockIRepository)(nil).GetUserByPhone), ctx, phoneNumber)
}

// GetUserByTelegramID mocks base method.
func (m *MockIRepository) GetUserByTelegramID(ctx context.Context, telegramID int64) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByTelegramID", ctx, telegramID)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByTelegramID indicates an expected call of GetUserByTelegramID.
func (mr *MockIRepositoryMockRecorder) GetUserByTelegramID(ctx, telegramID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByTelegramID", reflect.TypeOf((*MockIRepository)(nil).GetUserByTelegramID), ctx, telegramID)
}

// GetUserByTelegramUsername mocks base method.
func (m *MockIRepository) GetUserByTelegramUsername(ctx context.Context, username string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByTelegramUsername", ctx, username)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByTelegramUsername indicates an expected call of GetUserByTelegramUsername.
func (mr *MockIRepositoryMockRecorder) GetUserByTelegramUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByTelegramUsername", reflect.TypeOf((*MockIRepository)(nil).GetUserByTelegramUsername), ctx, username)
}

// IncrementOTPAttempts mocks base method.
func (m *MockIRepository) IncrementOTPAttempts(ctx context.Context, otpID pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementOTPAttempts", ctx, otpID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementOTPAttempts indicates an expected call of IncrementOTPAttempts.
func (mr *MockIRepositoryMockRecorder) IncrementOTPAttempts(ctx, otpID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementOTPAttempts", reflect.TypeOf((*MockIRepository)(nil).IncrementOTPAttempts), ctx, otpID)
}

// MarkOTPAsUsed mocks base method.
func (m *MockIRepository) MarkOTPAsUsed(ctx context.Context, otpID pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkOTPAsUsed", ctx, otpID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkOTPAsUsed indicates an expected call of MarkOTPAsUsed.
func (mr *MockIRepositoryMockRecorder) MarkOTPAsUsed(ctx, otpID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOTPAsUsed", reflect.TypeOf((*MockIRepository)(nil).MarkOTPAsUsed), ctx, otpID)
}

// UpdateAuthMethod mocks base method.
func (m *MockIRepository) UpdateAuthMethod(ctx context.Context, methodID pgtype.UUID, methodData any, isActive bool) (db.AuthMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAuthMethod", ctx, methodID, methodData, isActive)
	ret0, _ := ret[0].(db.AuthMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAuthMethod indicates an expected call of UpdateAuthMethod.
func (mr *MockIRepositoryMockRecorder) UpdateAuthMethod(ctx, methodID, methodData, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAuthMethod", reflect.TypeOf((*MockIRepository)(nil).UpdateAuthMethod), ctx, methodID, methodData, isActive)
}
